FROM registry.access.redhat.com/ubi9/ubi:latest as builder

WORKDIR /app
RUN dnf install -y \
    git-2.43.0-1.el9 \
    cmake-3.26.5-2.el9 \
    make-4.3-8.el9 \
    gcc-toolset-13-gcc-13.2.1-5.3.el9 \
    gcc-toolset-13-gcc-c++-13.2.1-5.3.el9

RUN source /opt/rh/gcc-toolset-13/enable && \
 mkdir whisper && cd whisper && git clone https://github.com/ggml-org/whisper.cpp . && \
    git checkout v1.8.0 && \
    make && \
    cp -r build /app/build && \
    cp samples/jfk.wav /app/jfk.wav && \
    cd ../ && rm -rf whisper
    
FROM registry.access.redhat.com/ubi9/ubi:latest
WORKDIR /app
COPY --from=builder /app /app

# https://github.com/wader/static-ffmpeg
# https://hub.docker.com/r/mwader/static-ffmpeg/
COPY --from=mwader/static-ffmpeg:6.1.1 /ffmpeg /bin/
COPY --from=mwader/static-ffmpeg:6.1.1 /ffprobe /bin/

COPY --chown=0:0 --chmod=755 src /app

ENV LD_LIBRARY_PATH=/app/build/src:/app/build/ggml/src

RUN chown -R 1001:0 /app && chmod -R g+w /app

USER 1001

ENV AUDIO_FILE=/app/jfk.wav
ENTRYPOINT ["sh", "run.sh"]